language: node_js
node_js: stable
sudo: false
addons:
  firefox: latest
  apt:
    packages:
    - oracle-java8-installer
    - oracle-java8-set-default
script:
- npm run test:lint:js
- npm run test:lint:wc
- npm run test:polymer
