language: node_js
node_js: 9
addons:
  chrome: latest
  apt:
    packages:
    - oracle-java8-installer
    - oracle-java8-set-default
script:
- npm run test:lint:js
- npm run test:lint:wc
- xvfb-run polymer test --skip-plugin sauce
